### ISSUE TITLE
New release with Swift 3 support?

### ISSUE THREAD

**Issue by mokagio** [FeatherweightLabs/FeatherweightRouter#16]
Hi all 👋 

I see that #15 has been merged in, which brings Swift 3 support.

It'd be awesome to see a new release, 2.0.0?, that can be used rather than the current `e76173c` (current `HEAD` on `master`) when working with Swift 3.

Thanks 💖

**Comment by agentk** [comment]
Sure can. I also want to introduce a change that passes the current route to presenters to path variables. I'll release v2 first, create a demo for the change and get it out as v3.

**Comment by mokagio** [comment]
Sweet, thanks!

**Comment by mokagio** [comment]
[v2 has been released](https://github.com/FeatherweightLabs/FeatherweightRouter/releases/tag/2.0.0) 🎉
