### ISSUE TITLE
Do the router work with deep URL's?

### ISSUE THREAD

**Issue by Aleksion** [FeatherweightLabs/FeatherweightRouter#3]
What I mean by this, is do the router easily manage to go from:

given the following routes:

``` http
"home"
"products/"
"products/{id}"
"products/{id}/details"
"products/{id}/features"
```

does it easily manage to go from:

``` http
"home/" --> "products/{id}/features" --> "products/{id}/details" --> "home/"
```

in this case I suppose `products/{id}` would have a navigationController onto which details and features are pushed.

It might be I'm overthinking it - and that everything should be pushed on the base navigationViewController (I might be leaning towards that now that I'm writing it). This would make sense if viewControllers are being popped EVERYTIME you change from one to the other. If the navigationStack is to be preserved , the above will have to be addressed. Unless that's already working

**Comment by agentk** [comment]
Deep linking support is one of the things I've been aiming for from the start. 

The pop / push between two deep path states is already there for the stack router. The NSViewControllers in AppKit can be controlled in the same way.

Which view controller they are popped on and off from would depend on the how the routers are setup. A JunctionRouter would pass the remainder of the route to a child router (likely a navigation controller) that would handle the remainder of the route.

I can see a lot more cases I haven't thought about here. The next couple of issues could make this easier.

**Comment by agentk** [comment]
Closing... Deep linked URL's all working in the demo now.
